### ISSUE TITLE
self.runNumber is not a string, causing f.write() error

### ISSUE THREAD

**Issue by scurrier03** [Teradata/PyTd#6]
I got a the following exception from line 238 of udaexec.py:
`TypeError: expected a character buffer object`

After some investigation, it seems that line 232 of udaexec.py should be:
`self.runNumber = str(1)`
...instead of...
`self.runNumber = 1`

After making this change myself, it seems to have passed this code OK, although I am now getting another exception from line 611 of udaexec.py, which I believe to be unrelated but will post here anyway in case it might be related:
`teradata.api.DatabaseError: (2617, u'[22003] [Teradata][ODBC Teradata Driver][Teradata Database] Overflow occurred computing an expression involving axis_bin.bin_index ')`

EDIT: The second exception is definitely not related, I accidentally tried to populate a BYTEINT with too large of a value.

**Comment by scurrier03** [comment]
See edit... second exception is definitly not related, that one was my mistake.

**Comment by escheie** [comment]
You're right, line 232 should be str(1) instead of 1.  Line 232 was added as a way to recover from the condition of a ".runNumber" file existing but not containing an integer value.  Do you happen to know how you got into this error condition in the first place?  Did you manually change the ".runNumber" file or override runNumber with a non-integer value?

Thanks,
-Eric

**Comment by scurrier03** [comment]
Not sure how I got to that error.  I didn't tamper with anything, not the file or the runNumber variable.

What does runNumber do?  If you tell me that then maybe I can put two and two together and related it to something else I did.

Not sure if it matters, but I had logs turned on and then they filled up my disk so I turned them off and I think I deleted the folder too.
